Data:
  # "1 2 4-6@2 3" means choose row 1,2,4,5,6 col 2,3 to plot, col 2 is x-axis, col 3 is y-axis
  X_Y: 
  - '1 2 4-6@2 3'   
  X_Y2: []
  X_Y2_Name: []
  X_Y_Name: 
  - Algorithm 1
Key: right top
Log: []
Output_file: output.eps
Pointsize: 2
Type: line
Xlabel: xlabel
Xrange: ''
Xtics: []
Y2label:
  Y2label: y2label
  Y2range: []
  Y2tics: []
  is_available: false
Ylabel: ylabel
Yrange: ''
Ytics: []
